name: Check for available bed in CAS cabin

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron:  '0/30 * * * *'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  check:
    runs-on: ubuntu-slim

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - run: playwright install

      #- run: playwright install firefox

      - run: playwright install-deps
      
      - name: Check availability
        id: check
        run: python check.py

      - name: Use the output
        shell: bash
        run: |
          if (( "${{ steps.check.outputs.dorm_free }}" > 0 )); then
              echo "::error::Found ${{ steps.check.outputs.dorm_free }} available beds !" >&2
              exit 1
          fi
